ecommerce/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
	path('', views.inbox, name='inbox'),
	path('<int:pk>/', views.detail, name ='detail'),
	path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

ecommerce/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('contact/', views.contact, name = 'contact'),
	path('privacy/', views.privacy, name = 'privacy'),
	path('terms/', views.terms, name = 'terms'),
	path('signup/', views.signup, name = 'signup'),
	path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html', authentication_form = LoginForm), name = 'login'),
	path('profile/edit/', views.edit_profile, name='edit_profile'),
	path('logout/', views.logout_user, name='logout'),
	
]

ecommerce/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
	path('', views.index, name = 'index'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

# Import images
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecommerce/item/urls.py
from django.urls import path

from . import views

app_name = 'item'
urlpatterns = [
	path('', views.browse, name='browse'),
	path('<int:pk>', views.detail, name = 'detail'),
	path('<int:pk>/delete/', views.delete, name = 'delete'),
	path('<int:pk>/edit/', views.edit, name = 'edit'),
	path('new/', views.new, name ='new'),
]

ecommerce/core/models.py
from django.db import models

# Create your models here.

ecommerce/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
	username = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6'
	}))

	password = forms.CharField(widget = forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6'
	}))

class SignupForm(UserCreationForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

	username = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6'
	}))

	email = forms.CharField(widget = forms.EmailInput(attrs={
		'placeholder': 'Your email address',
		'class': 'w-full py-4 px-6'
	}))
	
	first_name = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your first name',
		'class': 'w-full py-4 px-6'
	}))

	last_name = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your last name',
		'class': 'w-full py-4 px-6'
	}))
	password1 = forms.CharField(widget = forms.PasswordInput(attrs={
		'placeholder': 'Your password',
		'class': 'w-full py-4 px-6'
	}))

	password2 = forms.CharField(widget = forms.PasswordInput(attrs={
		'placeholder': 'Repeat password',
		'class': 'w-full py-4 px-6'
	}))

class EditProfileForm(UserChangeForm):
	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name')

	username = forms.CharField(disabled=True,widget = forms.TextInput(attrs={
		'placeholder': 'Your username',
		'class': 'w-full py-4 px-6'
	}))
	email = forms.CharField(disabled=True, widget = forms.EmailInput(attrs={
		'placeholder': 'Your email address',
		'class': 'w-full py-4 px-6'
	}) )

	first_name = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your first name',
		'class': 'w-full py-4 px-6'
	}))

	last_name = forms.CharField(widget = forms.TextInput(attrs={
		'placeholder': 'Your last name',
		'class': 'w-full py-4 px-6'
	}))
	

ecommerce/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from item.models import Category, Item
from django.contrib import messages
from .forms import SignupForm, EditProfileForm


# Create your views here.
def index(request):
	items = Item.objects.filter(is_sold = False)[0:6]
	categories = Category.objects.all()

	return render(request, 'core/index.html', {
	'categories': categories,
	'items': items,
	})

def contact(request):
	return render(request, 'core/contact.html')

def privacy(request):
	return render(request, 'core/privacy.html')

def terms(request):
	return render(request, 'core/terms.html')

def signup(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = SignupForm()

	form = SignupForm()

	return render(request, 'core/signup.html', {
		'form': form
	})

def logout_user(request):
	logout(request)
	messages.success(request, ("You have successfully logged out"))
	return redirect('/login/')

def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=request.user)

		if form.is_valid():
			form.save()

			return redirect('/login/')
	else:
		form = EditProfileForm(instance=request.user)

	form = EditProfileForm(instance=request.user)

	return render(request, 'core/edit_profile.html', {
		'form': form
	})

ecommerce/core/templates/core/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script src="https://cdn.tailwindcss.com"></script>
		<title>{% block title %}{% endblock %} | K-Commerce </title>
	</head>

	<body>
		<nav class = "py-6 px-6 flex justify-between items-center border-b border-gray-200">
			<a href = "/" class = "text-xl font-semibold">K-commerce</a>
			
			<div class= "space-x-6">
					<a href = "{% url 'item:new' %}" class = "px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded hover:bg-teal-700"> SELL </a>
				{% if request.user.is_authenticated %}
					
					<a href = "{% url 'item:browse' %}" class = "text-lg font-semibold hover:text-gray-500"> Browse</a>
					<a href = "{%url 'conversation:inbox' %}" class = "px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
					<a href = "{% url 'dashboard:index' %}" class = "px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">My Items</a>
					<a href = "{% url 'core:edit_profile' %}" class = "px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-gray-700">Profile</a>
					<a href = "{% url 'core:logout' %}" class = "px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
				{% else %}
					<a href = "{% url 'core:signup' %}" class = "text-lg font-semibold hover:text-gray-500">Sign-up</a>
					<a href = "{% url 'core:login' %}" class = "text-lg font-semibold hover:text-gray-500">Login</a>
				{% endif %}
			</div>
		</nav>
		<div class = "px-6 py-6">
			{% block content %}
			{% endblock %}
		</div>

		<footer class = "py-3 px-6 flex justify-between bg-gray-800">
			<div class = "w-2/3 pr-10">
				<h2 class = "mb-5 font-semibold text-gray-100">About</h2>
				<p class = "text-lg text-gray-100">An e-commerce website for you to sell or buy k-pop related merchandise.</p>
			</div>

			<div class = "w-1/3">
				<h3 class = "mb-5 font-semibold text-gray-300">Menu</h3>
				<ul class= "space-y-2">
					<li><a href = "{% url 'core:contact' %}" class = "text-lg text-teal-500 hover:text-teal-700">Contact</li>
					<li><a href = "{% url 'core:privacy' %}" class = "text-lg text-teal-500 hover:text-teal-700">Privacy</li>
					<li><a href = "{% url 'core:terms' %}" class = "text-lg text-teal-500 hover:text-teal-700">Terms</li>


				</ul>
			</div>
		</footer>
	</body>
</html>

ecommerce/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
	<h1> If you have any concerns contact the website via:</h1> <br>
	<h2> Phone: 09568074314</h2>
	<h2> E-mail: josh.ulitin@gmail.com</h2>
{% endblock %}

ecommerce/core/templates/core/edit_profile.html
{% extends 'core/base.html' %}

{% block title %} Profile {% endblock %}

{% block content %} 
	<div class = "w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
		<h1 class = "mb-6 text-3xl">Edit Profile</h1>

		<form method = "post" action = ".">
			{% csrf_token %}

			<div class = "mb-3">
				<label class = "inline-block mb-2"> Username </label><br>
				{{ form.username }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> E-mail </label><br>
				{{ form.email }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> First Name </label><br>
				{{ form.first_name }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Last Name </label><br>
				{{ form.last_name }}
			</div>
			

			{% if form.errors or form.non_field_errors %}
				 <div class = "mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %}
						{{ field.errors}}
					{% endfor %}

					{{ form.non_field_errors }}
				 </div>
			{% endif %}

			<button class = "py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded -xl text-white">Update</button>
		</form>
		<br>
	</div>
{% endblock %}

ecommerce/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock %}

{% block content %}
	<div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class = "mb-12 text-2xl text-center"> Latest Items </h2>

		<div class = "grid grid-cols-6 gap-1">
			{% for item in items %}
				<div>
					<a href = "{% url 'item:detail' item.id %}">
						<div>
							<img src ="{{ item.image.url }}" class = "rounded-t-xl w-64 h-48">

						</div>
						<div class = "p-6 bg-white rounded-b-xl  w-64 h-30 ">
							<h2 class = "text-xl">{{ item.name }}</h2>
							<p class = "text-gray-500">Price: {{item.price}}</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class = "mt-6 px-6 py-12 bg-gray-100 rounded-xl">
		<h2 class = "mb-12 text-2xl text-center"> Categories </h2>
		<div class = "grid grid-cols-3 gap-3">
			{% for category in categories %}
			
					<a href = "#">
						<div class = "p-6 bg-white rounded-b-xl">
							<h2 class = "text-2xl">{{ category.name }}</h2>
							<p class = "text-gray-500">{{ category.items.count}} items</p>
						</div>
					</a>
		
			{% endfor %}
		</div>
	</div>
{% endblock %}

ecommerce/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Login {% endblock %}

{% block content %} 
	<div class = "w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
		<h1 class = "mb-6 text-3xl">Login</h1>

		<form method = "post" action = ".">
			{% csrf_token %}

			
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Username </label><br>
				{{ form.username }}
			</div>
			
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Password </label><br>
				{{ form.password }}
			</div>

			{% if form.errors or form.non_field_errors %}
				 <div class = "mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %}
						{{ field.errors}}
					{% endfor %}

					{{ form.non_field_errors }}
				 </div>
			{% endif %}

			<button class = "py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded -xl text-white">Submit</button>
		</form>
	</div>
{% endblock %}

ecommerce/core/templates/core/privacy.html
{% extends 'core/base.html' %}

{% block title %} Privacy {% endblock %}

{% block content %}
<h1>We may collect and receive the following information. Please note that not all of our Services collect all of the information listed below:</h1><br>
<ul>
	<li>
<p>Account credentials such as username.</p><br>
<p></p>Profile information such as, name and email address</p><br>
<p></p>Location information such as last known location.</p><br>
<p></p>Any other information disclosed by you in any of the above-mentioned methods and/or through the use of our Services.<br>
<p></p>Aggregate data collected through the use of our Services.</p><br>
<p></p>Any communications between you and another user of our Services. </p><br>
	</li>
</ul>
{% endblock %}

ecommerce/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Signup {% endblock %}

{% block content %} 
	<div class = "w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
		<h1 class = "mb-6 text-3xl">Sign-up</h1>

		<form method = "post" action = ".">
			{% csrf_token %}

			
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Username </label><br>
				{{ form.username }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> E-mail </label><br>
				{{ form.email }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> First Name </label><br>
				{{ form.first_name }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Last Name </label><br>
				{{ form.last_name }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Password </label><br>
				{{ form.password1 }}
			</div>
			<div class = "mb-3">
				<label class = "inline-block mb-2"> Repeat Password</label><br>
				{{ form.password2 }}
			</div>

			{% if form.errors or form.non_field_errors %}
				 <div class = "mb-3 p-6 bg-red-100 rounded-xl">
					{% for field in form %}
						{{ field.errors}}
					{% endfor %}

					{{ form.non_field_errors }}
				 </div>
			{% endif %}

			<button class = "py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded -xl text-white">Submit</button>
		</form>
	</div>
{% endblock %}

ecommerce/core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %} Terms {% endblock %}

{% block content %}
<h1>You shall use the Services in accordance with these Terms and shall not:</h1><br>
<ul>
	<li>
<p>Upload any Content (as defined below) that violates or infringes another party’s rights of publicity, privacy, copyright, trademark or any other intellectual property right.</p><br>
<p></p>Copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, decrypt, interfere with, or disrupt the integrity or the performance of the Services.</p><br>
<p></p>Make any modification, adaptation, improvement, enhancement, translation or derivative work from the Services.</p><br>
<p></p>Violate any applicable laws, rules or regulations in connection with your access or use of the Services.<br>
<p></p>Use the Services in violation of or to circumvent any sanctions or embargo.</p><br>
<p></p>Use the Services for any purpose for which it is not designed or intended. </p><br>
	</li>
</ul>
{% endblock %}